# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.define "vm1" do |vm|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.box_version = "202510.26.0"
    config.vm.hostname = "test-ansible.dev"
    config.vm.network "private_network",  ip: "192.168.34.21"
  end
end
