# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |provider, override|
    provider.name = "test-ansible2.dev"
    provider.memory = 1024
  end
  config.vm.box = "bento/ubuntu-24.04"
  config.vm.box_version = "202510.26.0"
  config.vm.hostname = "test-ansible2.dev"
  config.vm.network "private_network",  ip: "192.168.34.23"
  config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=777","fmode=666"]
end
 

 